---

- name: Example using ternary() function
  hosts: localhost
  gather_facts: no
  vars:
    condition: true
    yaml_data:
      key1: value1
      key2:
        - item1
        - item2
        - item3

  tasks:
    # - name: Set result based on condition
    #   set_fact:
    #     result: "{{ ternary(condition, 'Condition is true', 'Condition is false') }}"

    # - debug:
    #     var: result

# use map example

    - name: Read JSON file
      ansible.builtin.include_vars:
        file: files/map_example.json
        name: user_data

    - set_fact:
        user_names: "{{ user_data.users | map(attribute='name') | list }}"

    - debug:
        var: user_names

    - name: set list
      set_fact:
        numbers: [1, 2, 3, 4, 5]

    - name: set squared list
      set_fact:
        squared_numbers: []

    - set_fact:
        squared_numbers: "{{ squared_numbers + [item * item] }}"
      loop: "{{ numbers }}"

    - debug:
        var: squared_numbers

# convert yaml to json
    - name: Convert YAML to JSON
      set_fact:
        json_data: "{{ yaml_data | to_json }}"

    - debug:
        var: json_data

    - name: Check if a file exists
      set_fact:
        file_exists: "{{ lookup('file', '../../README.md') | bool }}"
      ignore_errors: yes

    - debug:
        var: file_exists

    - name: Get file size
      set_fact:
        file_size_bytes: "{{ lookup('file', '../../README.md') | filesize }}"
      ignore_errors: yes

    - debug:
        var: file_size_bytes

    - name: Get file permissions
      set_fact:
        file_permissions: "{{ lookup('file', '../../files/map_example.json') | fileattr('mode') }}"
      ignore_errors: yes

    - debug:
        var: file_permissions
